Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
